//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string must be passed to the constructor.
        /// </summary>
        public static string AConnectionStringMustBePassedToTheConstructor {
            get {
                return ResourceManager.GetString("AConnectionStringMustBePassedToTheConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in your application.
        /// </summary>
        public static string An_error_occurred_in_your_Application {
            get {
                return ResourceManager.GetString("An_error_occurred_in_your_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte value greater than 20mb are not supported.
        /// </summary>
        public static string ByteValueGreaterThan20megsAreNotSupported {
            get {
                return ResourceManager.GetString("ByteValueGreaterThan20megsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration method no longer supported.
        /// </summary>
        public static string ConfigurationMethodNoLongerSupported {
            get {
                return ResourceManager.GetString("ConfigurationMethodNoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection opening failure: {0}.
        /// </summary>
        public static string ConnectionOpeningFailure {
            get {
                return ResourceManager.GetString("ConnectionOpeningFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create user token.
        /// </summary>
        public static string CouldntCreateUserToken {
            get {
                return ResourceManager.GetString("CouldntCreateUserToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load entity. Invalid key provided..
        /// </summary>
        public static string CouldntLoadEntityInvalidKeyProvided {
            get {
                return ResourceManager.GetString("CouldntLoadEntityInvalidKeyProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data reader passed to object failure..
        /// </summary>
        public static string DataReaderPassedToDataReaderToObjectCannot {
            get {
                return ResourceManager.GetString("DataReaderPassedToDataReaderToObjectCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string ErrorColon {
            get {
                return ResourceManager.GetString("ErrorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection String.
        /// </summary>
        public static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection string name..
        /// </summary>
        public static string InvalidConnectionStringName {
            get {
                return ResourceManager.GetString("InvalidConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encryption property name.
        /// </summary>
        public static string InvalidEncryptionPropertyName {
            get {
                return ResourceManager.GetString("InvalidEncryptionPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex digit.
        /// </summary>
        public static string InvalidHexDigit {
            get {
                return ResourceManager.GetString("InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex string length..
        /// </summary>
        public static string InvalidHexStringLength {
            get {
                return ResourceManager.GetString("InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for Xml type to .NET object conversion..
        /// </summary>
        public static string InvalidTypeForXmlTypeToNETTypeConversion {
            get {
                return ResourceManager.GetString("InvalidTypeForXmlTypeToNETTypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token identifier - token must be at least 8 characters.
        /// </summary>
        public static string InvalidUserTokenIdentifier {
            get {
                return ResourceManager.GetString("InvalidUserTokenIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Xml configuration file format..
        /// </summary>
        public static string InvalidXMLConfigurationFileFormat {
            get {
                return ResourceManager.GetString("InvalidXMLConfigurationFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.NET library not available..
        /// </summary>
        public static string JSON_NET_library_not_avaiable {
            get {
                return ResourceManager.GetString("JSON_NET_library_not_avaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing encryption key..
        /// </summary>
        public static string MissingEncryptionKey {
            get {
                return ResourceManager.GetString("MissingEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid token identifier..
        /// </summary>
        public static string MissingOrInvalidTokenIdentifier {
            get {
                return ResourceManager.GetString("MissingOrInvalidTokenIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active transaction to commit..
        /// </summary>
        public static string NoActiveTransactionToCommit {
            get {
                return ResourceManager.GetString("NoActiveTransactionToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object could not be deserialized from Xml.
        /// </summary>
        public static string ObjectCouldNotBeDeserializedFromXml {
            get {
                return ResourceManager.GetString("ObjectCouldNotBeDeserializedFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServer Compact Data Provider not supported on .NET Core..
        /// </summary>
        public static string SqlServerCompactDataProviderNotSupportedOnNetCore {
            get {
                return ResourceManager.GetString("SqlServerCompactDataProviderNotSupportedOnNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to typed value type conversion failed..
        /// </summary>
        public static string StringToTypedValueValueTypeConversionFailed {
            get {
                return ResourceManager.GetString("StringToTypedValueValueTypeConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract config data from string.
        /// </summary>
        public static string UnableToExtractKeys {
            get {
                return ResourceManager.GetString("UnableToExtractKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read configuration data from string..
        /// </summary>
        public static string UnableToReadConfigDataFromString {
            get {
                return ResourceManager.GetString("UnableToReadConfigDataFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve DbProvider Factory Form.
        /// </summary>
        public static string UnableToRetrieveDbProviderFactoryForm {
            get {
                return ResourceManager.GetString("UnableToRetrieveDbProviderFactoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Provider Factory.
        /// </summary>
        public static string UnsupportedProviderFactory {
            get {
                return ResourceManager.GetString("UnsupportedProviderFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has expired..
        /// </summary>
        public static string UserTokenHasExpired {
            get {
                return ResourceManager.GetString("UserTokenHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found..
        /// </summary>
        public static string UserTokenNotFound {
            get {
                return ResourceManager.GetString("UserTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
